# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "ZijunLi7"
repo_name: "3dv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/3dv-arxiv-daily.json'
json_gitpage_path: './docs/3dv-arxiv-daily-web.json'
json_wechat_path: './docs/3dv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "3D Reconstruction":
        filters: ["SFM", "Structure from Motion", "Structure and Motion",
                  "3D Reconstruction", "Scene Reconstruction", "3D Geometric"]
        titles: ["ti:SFM", "ti:Structure from Motion", "ti:Structure and Motion",
                  "ti:Reconstruction", "ti:Scene Reconstruction", "ti:3D"]
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]
        invert: ["ti:NeRF", "ti:Neural Radiance Field", "ti:Gaussian Splatting", "ti:NGP",
                 "ti:Medical", "ti:Surgery", "ti:MRI"]
    "Depth Estimation":
        filters: ["Depth Estimation", "Monocular Depth Estimation",
                  "Metric Depth", "Geometry Estimation"]
        titles: ["ti:Depth", "ti:Monocular", "ti:Metric", "ti:Geometr", "ti:Single"]
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]
        invert: ["ti:NeRF", "ti:Neural Radiance Field", "ti:Gaussian Splatting", "ti:NGP",
                 "ti:Medical", "ti:Surgery", "ti:MRI", "ti:Reconstruction"]
    "Visual Localization":
        filters: ["Visual Localization","Camera Localization",
                  "Camera Relocalization", "Visual Place Recognition",
                  "Image Retrieval"]
        titles: ["ti:Localization", "ti:Place Recognition", "ti:localisation","ti:Retrieval",
                 "ti:APR", "ti:Dof", "ti:Pose Estimation", "ti:Pose Regression", "ti:Coordinate"]
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]
        invert: ["ti:Medical", "ti:Object Pose"]
    "Image Matching":
        filters: ["Image Matching"]
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]
        invert: ["ti:Medical", "ti:Surgery", "ti:MRI"]
    "NeRF & Gaussian":
        filters: ["NeRF", "Neural Radiance Field", "Gaussian Splatting"]
        titles: ["ti:NeRF", "ti:Radiance", "ti:Field", "ti:Gaussian",
                 "ti:Splatting"]
        categories: ["cat:cs.CV", "cat:cs.GR", "cat:cs.RO"]