# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "ZijunLi7"
repo_name: "3dv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/3dv-arxiv-daily.json'
json_gitpage_path: './docs/3dv-arxiv-daily-web.json'
json_wechat_path: './docs/3dv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "3D Reconstruction":
        filters: ["SFM", "Structure from Motion", "Structure and Motion",
                  "3D Reconstruction", "Scene Reconstruction", "3D Geometric"]
    "Visual Localization":
        filters: ["Visual Localization","Camera Localization",
                  "Camera Re-localisation", "visual place recognition",
                  "image retrieval"]
    "Image Matching":
        filters: ["Image Matching"]
    "NeRF & Gaussian":
        filters: ["NeRF", "Neural Radiance Field", "Gaussian Splatting"]
    "Depth Estimation":
        filters: ["Depth Estimation", "Monocular Depth Estimation",
                  "Metric Depth", "Geometry Estimation"]

